### PR TITLE
Add ability to customize machine suffix

### PR DESCRIPTION
**Pull request by perry-garvin**
Thanks for writing this! I added the ability for a user to customize the machine suffix from its default, "Machine."

### CODE REVIEW

**Comment by perry-garvin** [comment]
I didn't update the README with this change but I'm happy to if you like. Before doing that I wanted to get your approval.

**Comment by f-elix** [comment]
Hey! Great idea! 

Can you please add the documentation to the README? I will merge everything together afterwards.

Thanks!

**Comment by perry-garvin** [comment]
Great! Here's a draft. Please edit it if you think it can be more clearly stated.

**Comment by f-elix** [comment]
All good, just merged! Thank you so much for your contribution, really appreciated!

**Pull request merged**
